### ISSUE TITLE
Import classes is missing

### ISSUE THREAD

**Issue by JainVikas** [hadyelsahar/large-arabic-sentiment-analysis-resouces#1]
Hi Team,
In trying to run the project as-is and get results, 
Following code isn't working as the classes.py file seems to be missing.
`from classes.Document import *
from classes.Utils import * 
from classes.LexiconVectorizer import * 
from classes.DeltaTfidf import * `

if possible, can you add that file?
Thanks in Advance for your help.

**Comment by JainVikas** [comment]
found the details in other repository

**Comment by abdelkaderkh** [comment]
Hi bro u fixit ? i need that fix if u fixed 
thank u

**Comment by Walid-Gomaa** [comment]
Could you please inform me how to fix this?

**Comment by JainVikas** [comment]
Hi @abdelkaderkh  and @Walid-Gomaa : you can refer the classes scripts used in the below repository. https://github.com/hadyelsahar/large-arabic-multidomain-lexicon/tree/master/classes
